# ABIDE Dataset Configuration
# Single-task binary classification for Autism detection

dataset: abide

# Data loading options
# Option 1: Use single file and split on-the-fly (use_split_data: false)
# Option 2: Use pre-split files (use_split_data: true)
use_split_data: true  # Set to true to use pre-split train/val/test files
data_path: W:\Brain Analysis\FSCN\data\ABIDE\abide.npy
train_data_path: W:\Brain Analysis\FSCN\data\ABIDE\abide_train.npy
val_data_path: W:\Brain Analysis\FSCN\data\ABIDE\abide_val.npy
test_data_path: W:\Brain Analysis\FSCN\data\ABIDE\abide_test.npy

# Data splitting (only used when use_split_data is false)
val_split: 0.1

# Model architecture
d_model: 256

# Training hyperparameters
batch_size: 32
epochs: 100
lr: 1.0e-5
weight_decay: 1.0e-6
patience: 20

# Class imbalance handling
use_balanced_sampler: false

# Loss function
loss_type: ce  # Options: ce, focal, weighted_ce, weighted_focal
focal_gamma: 2.0

# Reproducibility
seed: 42

# Device
device: auto  # Options: auto, cpu, cuda

# Tasks (not applicable for ABIDE, leave null)
tasks: null

