# 基线模型配置文件
# 支持训练 GCN、Transformer、GAT 等基线模型

# 数据集配置
dataset: abide
use_split_data: true
train_data_path: W:\Brain Analysis\FSCN\data\ABIDE\abide_train.npy
val_data_path: W:\Brain Analysis\FSCN\data\ABIDE\abide_val.npy
test_data_path: W:\Brain Analysis\FSCN\data\ABIDE\abide_test.npy
data_path: W:\Brain Analysis\FSCN\data\ABIDE\abide.npy
val_split: 0.1

# 模型架构
d_model: 128

# 训练超参数
batch_size: 32
epochs: 100
lr: 1.0e-4
weight_decay: 1.0e-5
patience: 20
dropout: 0.3

# 类别不平衡处理
use_balanced_sampler: false
minority_ratio: 0.3

# 损失函数
loss_type: ce  # Options: ce, focal, weighted_ce, weighted_focal
focal_gamma: 2.0

# 随机种子
seed: 42

# 设备
device: auto  # Options: auto, cpu, cuda

